name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: configure
        run: |
          cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
      - name: build
        run: |
          cmake --build build --config Debug
      - name: test
        run: |
          cd build
          ctest
      - name: Compile Arduino examples
        run: |
          pushd build
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          popd
          export PATH="build/bin:$PATH"
          ./examples/arduino/compile-examples.sh
